# Generated by Django 4.0.1 on 2022-01-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('model', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
